
// function that returns license badge based off string passed in
const renderLicenseBadge = function(licenseString) {

    // make sure all letters in the string passed in are lowercase
    const lowercaseLicense = licenseString.toLowerCase();

    if(lowercaseLicense === 'apache') {
        return '[![License](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)'
    } else if(lowercaseLicense === 'gnu') {
        return '[![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)'
    } else if(lowercaseLicense === 'isc') {
        return '[![License: ISC](https://img.shields.io/badge/License-ISC-blue.svg)](https://opensource.org/licenses/ISC)'
    } else if(lowercaseLicense === 'mit') {
        return '[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)'
    } else if(lowercaseLicense === 'boost') {
        return '[![License](https://img.shields.io/badge/License-Boost_1.0-lightblue.svg)](https://www.boost.org/LICENSE_1_0.txt)'
    } else if(lowercaseLicense === 'mozilla') {
        return '[![License: MPL 2.0](https://img.shields.io/badge/License-MPL_2.0-brightgreen.svg)](https://opensource.org/licenses/MPL-2.0)'
    } else {
        // if the string passed in does not match to one of the above licenses, return an empty string
        return '';
    }

}



// function that returns the license section of README
const renderLicenseSection = function(licenseString) {

    // make sure all letters in the string passed in are lowercase
    const lowercaseLicense = licenseString.toLowerCase();

    if(lowercaseLicense === 'apache') {
        // URL reference
        // https://choosealicense.com/licenses/apache-2.0/
        return 'Under the Apache License 2.0, users may distribute and modify software. Users may also use it commercially or patent it. Private use is also available. In order to do this, the license must be present and be inline with copyright notices.'
    } else if(lowercaseLicense === 'gnu') {
        // URL reference
        // https://choosealicense.com/licenses/gpl-3.0/
        return 'Under the GNU General Public License v3.0, users may distrubute and modify software. Users may also use it commercially or patent it. Private use is also available. In order to do this, the license must be present and be inline with copyright notices. Users must also disclose the source of the copied/referenced code as well as use the same license as the copied/referenced code.'
    } else if(lowercaseLicense === 'isc') {
        // URL reference
        // https://choosealicense.com/licenses/isc/
        return 'The ISC License states... Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies'
    } else if(lowercaseLicense === 'mit') {
        // URL reference
        // https://choosealicense.com/licenses/mit/
        return 'The MIT License states... Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.'
    } else if(lowercaseLicense === 'boost') {
        // URL reference
        // https://www.boost.org/LICENSE_1_0.txt
        return 'The Boost License states...  Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject to the following: The copyright notices in the Software and this entire statement, including the above license grant, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object code generated by a source language processor.'
    } else if(lowercaseLicense === 'mozilla') {
        // URL reference
        // https://www.mozilla.org/en-US/MPL/2.0/
        return 'The Mozilla Public License 2.0 states... Each Contributor hereby grants You a world-wide, royalty-free, non-exclusive license: under intellectual property rights (other than patent or trademark) Licensable by such Contributor to use, reproduce, make available, modify, display, perform, distribute, and otherwise exploit its Contributions, either on an unmodified basis, with Modifications, or as part of a Larger Work; and under Patent Claims of such Contributor to make, use, sell, offer for sale, have made, import, and otherwise transfer either its Contributions or its Contributor Version.'
    } else {
        // if the string passed in does not match to one of the above licenses, return an empty string
        return '';
    }

}



// function that returns the link to a license
const renderLicenseLink = function(licenseString) {

    // make sure all letters in the string passed in are lowercase
    const lowercaseLicense = licenseString.toLowerCase();

    if(lowercaseLicense === 'apache') {
        return 'https://www.apache.org/licenses/LICENSE-2.0'
    } else if(lowercaseLicense === 'gnu') {
        return 'https://www.gnu.org/licenses/gpl-3.0.en.html'
    } else if(lowercaseLicense === 'isc') {
        return 'https://choosealicense.com/licenses/isc/'
    } else if(lowercaseLicense === 'mit') {
        return 'https://choosealicense.com/licenses/mit/'
    } else if(lowercaseLicense === 'boost') {
        return 'https://www.boost.org/users/license.html'
    } else if(lowercaseLicense === 'mozilla') {
        return 'https://www.mozilla.org/en-US/MPL/2.0/'
    } else {
        // if the string passed in does not match to one of the above licenses, return an empty string
        return '';
    }

}



// export functions
module.exports = {
    renderLicenseBadge,
    renderLicenseSection,
    renderLicenseLink
};

